# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.ttukorvpallikool.ee
title: 'Korvpallitrenn Tallinnas ja Harjumaal. Trennid lastele ja noortele igas vanuses - mikrost magistrini! Kaasaegne õpe ja metoodika.'
email: info@ttukorvpallikool.ee
address: 'Männiliiva 7, Mustamäe, 13414, Harju maakond'
phone: '+372 50 250 32'

author: TTU
description: > # "Write an awesome description for your new site here. 
  Ühendklubi, mis pakub korvpallitrenni Tallinnas ja Harjumaal. Korvpallitrennid lastele ja noortele, igas vanuses.
copyright: 'Copyright &copy; 2017 TTÜ Korvpallikool. Kõik õigused kaitstud.'
# about: 'TTÜ Korvpallikool on ühendklubi, kus õpib *ligi 700 korvpallurit*, nii suurt kui väikest.
# Korvpalli trennid igale vanusele *Tallinnas ja Harjumaal*'
about: ok




# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #
plugins_dir:
  - jekyll-polyglot

languages: ["ee", "en", "ru"]
default_lang: "ee"
exclude_from_localization:
  - img


parallel_localization: true


# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/ttukorvpallikool/
    img: /img/fb.svg
  - title: instagram
    url: https://www.instagram.com/taltechbasketballschool
    img: '/img/insta.svg'


jekyll-minifier:
  preserve_php: true                # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  compress_css: true                # Default: true
  compress_javascript: true         # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: false      # Default: false

