# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.ttukorvpallikool.ee
title: TTÜ Korvpallikool
email: infok@ttukorvpallikool.ee
address: 'Männiliiva 7, Mustamäe, 13414, Harju maakond'
phone: '+372 50 250 32'

author: TTU
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2017 TTÜ Korvpallikool. Kõik õigused kaitstud.'
# about: 'TTÜ Korvpallikool on ühendklubi, kus õpib *ligi 700 korvpallurit*, nii suurt kui väikest.
# Korvpalli trennid igale vanusele *Tallinnas ja Harjumaal*'
about: ok



# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #
plugins_dir:
  - jekyll-polyglot

languages: ["ee", "en"]
default_lang: "ee"
# exclude_from_localization: ["js", "img", "css"]
parallel_localization: true


# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/SPORDIKLUBI-RIM-132400890107202/
  - title: instagram
    url: htps://www.google.com
  
